import { Input, Link, Navbar, Text } from "@nextui-org/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Connector } from ".";
import { AppLogo } from "./Elements/AppLogo";
import { Box } from "./Elements/Box";
import { SearchIcon } from "./Icons/SearchIcon";

const collapseItems = [
  "Profile",
  "Dashboard",
  "Activity",
  "Analytics",
  "System",
  "Deployments",
  "My Settings",
  "Team Settings",
  "Help & Feedback",
  "Log Out",
];

const LayOut = ({
  title = "Create Next App",
  description = "Generated by create next app",
  children,
}) => {
  const router = useRouter();

  const checkRouterIsActive = (name) => {
    if (router.pathname === name) {
      return true;
    } else {
      return false;
    }
  };

  return (
    <Box
      css={{
        maxW: "100%",
      }}
    >
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar variant="sticky">
        <Navbar.Toggle showIn="xs" />
        <Navbar.Brand
          css={{
            "@xs": {
              w: "12%",
            },
          }}
        >
          <AppLogo />
          <Text b color="inherit" hideIn="xs">
            ACME
          </Text>
        </Navbar.Brand>
        <Navbar.Content
          enableCursorHighlight
          activeColor="warning"
          hideIn="xs"
          variant="highlight"
          css={{
            "@xs": {
              w: "50%",
              jc: "flex-start",
            },
          }}
        >
          <Navbar.Link isActive={checkRouterIsActive("/")} href="/">
            หน้าแรก
          </Navbar.Link>
          <Navbar.Link
            isActive={checkRouterIsActive("/exchange")}
            href="/exchange"
          >
            ตลาด
          </Navbar.Link>
          <Navbar.Link isActive={checkRouterIsActive("/swap")} href="/swap">
            แลกเปลี่ยน
          </Navbar.Link>
          <Navbar.Link isActive={checkRouterIsActive("/freeze")} href="/freeze">
            ออมรับดอกเบี้ย
          </Navbar.Link>
        </Navbar.Content>
        <Navbar.Content
          css={{
            "@xs": {
              w: "100%",
              jc: "flex-end",
            },
          }}
        >
          <Navbar.Item
            css={{
              "@xsMax": {
                w: "100%",
                jc: "center",
              },
            }}
          >
            <Input
              clearable
              contentLeft={
                <SearchIcon fill="var(--nextui-colors-accents6)" size={16} />
              }
              contentLeftStyling={false}
              css={{
                w: "100%",
                "@xsMax": {
                  mw: "300px",
                },
                "& .nextui-input-content--left": {
                  h: "100%",
                  ml: "$4",
                  dflex: "center",
                },
              }}
              placeholder="Search..."
            />
          </Navbar.Item>
          <Connector />
        </Navbar.Content>
        <Navbar.Collapse disableAnimation>
          {collapseItems.map((item, index) => (
            <Navbar.CollapseItem
              key={item}
              activeColor="warning"
              css={{
                color: index === collapseItems.length - 1 ? "$error" : "",
              }}
              isActive={index === 2}
            >
              <Link
                color="inherit"
                css={{
                  minWidth: "100%",
                }}
                href="#"
              >
                {item}
              </Link>
            </Navbar.CollapseItem>
          ))}
        </Navbar.Collapse>
      </Navbar>
      <div className="pl-12 pr-12">{children}</div>
    </Box>
  );
};

export default LayOut;
