import Head from "next/head";
import {
  Navbar,
  Link,
  Text,
  Avatar,
  Dropdown,
  Input,
  Badge,
  Button,
} from "@nextui-org/react";
import { AppLogo } from "./Elements/AppLogo";
import { Box } from "./Elements/Box";
import { SearchIcon } from "./Icons/SearchIcon";
import { NotificationIcon } from "./Icons/NotificationIcon";
import { AddNoteIcon } from "./Icons/AddNoteIcon";
import { CopyDocumentIcon } from "./Icons/CopyDocumentIcon";
import { EditDocumentIcon } from "./Icons/EditDocumentIcon";
import { DeleteDocumentIcon } from "./Icons/DeleteDocumentIcon";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { useAccount, useConnect, useEnsName, useDisconnect } from "wagmi";
import { InjectedConnector } from "wagmi/connectors/injected";

const collapseItems = [
  "Profile",
  "Dashboard",
  "Activity",
  "Analytics",
  "System",
  "Deployments",
  "My Settings",
  "Team Settings",
  "Help & Feedback",
  "Log Out",
];

const LayOut = ({
  title = "Create Next App",
  description = "Generated by create next app",
  children,
}) => {
  const { disconnect } = useDisconnect();
  const router = useRouter();
  const [account, setAccount] = useState(null);
  const { address, isConnected } = useAccount();
  const { data: ensName } = useEnsName({ address });
  const { connect } = useConnect({
    connector: new InjectedConnector(),
  });

  const checkRouterIsActive = (name) => {
    if (router.pathname === name) {
      return true;
    } else {
      return false;
    }
  };

  const logOutWallet = async (actionKey) => {
    console.log(actionKey);
    disconnect();
  };

  useEffect(() => {
    if (account) {
    }
  }, [account]);

  return (
    <Box
      css={{
        maxW: "100%",
      }}
    >
      <Head>
        <title>{title}</title>
        <meta name="description" content={description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar isBordered variant="sticky">
        <Navbar.Toggle showIn="xs" />
        <Navbar.Brand
          css={{
            "@xs": {
              w: "12%",
            },
          }}
        >
          <AppLogo />
          <Text b color="inherit" hideIn="xs">
            ACME
          </Text>
        </Navbar.Brand>
        <Navbar.Content
          enableCursorHighlight
          activeColor="warning"
          hideIn="xs"
          variant="highlight"
          css={{
            "@xs": {
              w: "50%",
              jc: "flex-start",
            },
          }}
        >
          <Navbar.Link isActive={checkRouterIsActive("/")} href="/">
            หน้าแรก
          </Navbar.Link>
          <Navbar.Link
            isActive={checkRouterIsActive("/exchange")}
            href="/exchange"
          >
            ตลาด
          </Navbar.Link>
          <Navbar.Link isActive={checkRouterIsActive("/swap")} href="/swap">
            แลกเปลี่ยน
          </Navbar.Link>
          <Navbar.Link isActive={checkRouterIsActive("/freeze")} href="/freeze">
            ออมรับดอกเบี้ย
          </Navbar.Link>
        </Navbar.Content>
        <Navbar.Content
          css={{
            "@xs": {
              w: "100%",
              jc: "flex-end",
            },
          }}
        >
          <Navbar.Item
            css={{
              "@xsMax": {
                w: "100%",
                jc: "center",
              },
            }}
          >
            <Input
              clearable
              contentLeft={
                <SearchIcon fill="var(--nextui-colors-accents6)" size={16} />
              }
              contentLeftStyling={false}
              css={{
                w: "100%",
                "@xsMax": {
                  mw: "300px",
                },
                "& .nextui-input-content--left": {
                  h: "100%",
                  ml: "$4",
                  dflex: "center",
                },
              }}
              placeholder="Search..."
            />
          </Navbar.Item>
          {isConnected ? (
            <>
              <Dropdown
                placement="bottom-right"
                aria-label="Actions"
                css={{ $$dropdownMenuWidth: "280px" }}
              >
                <Navbar.Item>
                  <Dropdown.Trigger>
                    <Button light color="primary" auto>
                      <Badge
                        color="error"
                        content={5}
                        isInvisible={false}
                        shape="circle"
                      >
                        <NotificationIcon
                          as="button"
                          fill="currentColor"
                          size={30}
                        />
                      </Badge>
                    </Button>
                  </Dropdown.Trigger>
                </Navbar.Item>
                <Dropdown.Menu>
                  <Dropdown.Section title="Actions">
                    <Dropdown.Item
                      key="new"
                      command="⌘N"
                      description="Create a new file"
                      icon={
                        <AddNoteIcon
                          size={22}
                          fill="var(--nextui-colors-secondary)"
                        />
                      }
                    >
                      New file
                    </Dropdown.Item>
                    <Dropdown.Item
                      key="copy"
                      command="⌘C"
                      description="Copy the file link"
                      icon={
                        <CopyDocumentIcon
                          size={22}
                          fill="var(--nextui-colors-secondary)"
                        />
                      }
                    >
                      Copy link
                    </Dropdown.Item>
                    <Dropdown.Item
                      key="edit"
                      command="⌘⇧E"
                      description="Allows you to edit the file"
                      icon={
                        <EditDocumentIcon
                          size={22}
                          fill="var(--nextui-colors-secondary)"
                        />
                      }
                    >
                      Edit file
                    </Dropdown.Item>
                  </Dropdown.Section>
                  <Dropdown.Section title="Danger zone">
                    <Dropdown.Item
                      key="delete"
                      color="error"
                      command="⌘⇧D"
                      description="Permanently delete the file"
                      icon={
                        <DeleteDocumentIcon size={22} fill="currentColor" />
                      }
                    >
                      Delete file
                    </Dropdown.Item>
                  </Dropdown.Section>
                </Dropdown.Menu>
              </Dropdown>
              <Dropdown placement="bottom-right">
                <Navbar.Item>
                  <Dropdown.Trigger>
                    <Avatar
                      bordered
                      as="button"
                      color="warning"
                      size="md"
                      src="https://i.pravatar.cc/150?u=a042581f4e29026704d"
                    />
                  </Dropdown.Trigger>
                </Navbar.Item>
                <Dropdown.Menu
                  aria-label="User menu actions"
                  color="warning"
                  onAction={(actionKey) => logOutWallet({ actionKey })}
                >
                  <Dropdown.Item key="profile" css={{ height: "$18" }}>
                    <Text b color="inherit" css={{ d: "flex" }}>
                      Signed in as
                    </Text>
                    <Text b color="inherit" css={{ d: "flex" }}>
                      {ensName ?? address}
                    </Text>
                  </Dropdown.Item>
                  <Dropdown.Item key="settings" withDivider>
                    My Settings
                  </Dropdown.Item>
                  <Dropdown.Item key="team_settings">
                    Team Settings
                  </Dropdown.Item>
                  <Dropdown.Item key="analytics" withDivider>
                    Analytics
                  </Dropdown.Item>
                  <Dropdown.Item key="system">System</Dropdown.Item>
                  <Dropdown.Item key="configurations">
                    Configurations
                  </Dropdown.Item>
                  <Dropdown.Item key="help_and_feedback" withDivider>
                    Help & Feedback
                  </Dropdown.Item>
                  <Dropdown.Item key="logout" withDivider color="error">
                    Log Out
                  </Dropdown.Item>
                </Dropdown.Menu>
              </Dropdown>
            </>
          ) : (
            <Navbar.Item>
              <Button color="primary" auto onPress={() => connect()}>
                Connect Wallet
              </Button>
            </Navbar.Item>
          )}
        </Navbar.Content>
        <Navbar.Collapse disableAnimation>
          {collapseItems.map((item, index) => (
            <Navbar.CollapseItem
              key={item}
              activeColor="warning"
              css={{
                color: index === collapseItems.length - 1 ? "$error" : "",
              }}
              isActive={index === 2}
            >
              <Link
                color="inherit"
                css={{
                  minWidth: "100%",
                }}
                href="#"
              >
                {item}
              </Link>
            </Navbar.CollapseItem>
          ))}
        </Navbar.Collapse>
      </Navbar>
      <div className="pl-12 pr-12">{children}</div>
    </Box>
  );
};

export default LayOut;
